# Generated by Django 5.1.7 on 2025-03-21 22:15

import checkout.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('computer_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Computer ID')),
                ('computer_number', models.CharField(max_length=10, verbose_name='Computer Number')),
                ('condition', models.CharField(max_length=100, verbose_name='Condition')),
                ('status', models.CharField(max_length=200, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('a_number', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('[^A]\\d{8}$', message='Invalid A number format')], verbose_name='Anumber')),
                ('email', models.EmailField(max_length=321, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Account Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('time_out', models.DateTimeField(auto_now_add=True, verbose_name='Time Out')),
                ('time_in', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time In')),
                ('condition_out', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Condition Out')),
                ('condition_in', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Condition In')),
                ('computer_id', models.ForeignKey(on_delete=models.SET_NULL, null = True, to='checkout.laptop')),
                ('user_id', models.ForeignKey(on_delete=models.SET_NULL, null = True, to='checkout.user')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET_NULL, to='checkout.user'),
        ),
    ]
