# Generated by Django 4.2.20 on 2025-03-25 16:03

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_laptop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='computer_id',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, to='checkout.laptop'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=models.SET_NULL, to='checkout.user'),
        ),
    ]
