# Generated by Django 4.2.20 on 2025-03-25 16:35

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_transaction_computer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET_NULL, to='checkout.user'),
        ),
    ]
