# Generated by Django 4.2.20 on 2025-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_laptop_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='status',
            field=models.CharField(default='checked_in', max_length=20),
        ),
    ]
