# Generated by Django 4.2.20 on 2025-03-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_transaction_computer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='computer_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.laptop'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.user'),
        ),
    ]
